version: '3.5'
services:
  search_api:
    container_name: 'search_api'
    build: ./search-api
    restart: 'on-failure'
    depends_on:
      - mysql
      - elasticsearch
    links:
      - mysql
    ports:
      - '8080:8080'     
  elasticsearch:
    container_name: 'elasticsearch'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.2.3'
    ports:
      - '9200:9200'
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_USER=crawler
      - MYSQL_DATABASE=go_crawler
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=33838449
      - 3306:3306
